config/routes.rb
Rails.application.routes.draw do

  resources :categories
  root "events#index"

  get 'events/filter/:scope' => "events#index", as: :filtered_events

  resources :events do
    resources :registrations
    resources :likes
  end
  
  resources :users
  get 'signup' => 'users#new'

  resource :session

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :event
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :events, through: :categorizations
  
  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name,presence: true, uniqueness: true

  validates :slug, uniqueness: true

  validates :location, presence: true

  validates :description, length: { minimum: 25 }

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates :capacity, numericality: { only_integer: true, greater_than: 0 }

  validates :image_file_name, allow_blank: true, format: {
    with:    /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  before_validation :generate_slug

  scope :upcoming, -> { where('starts_at >= ?', Time.now).order(:starts_at) }
  scope :past, -> { where('starts_at < ?', Time.now).order(:starts_at) }
  scope :free, -> { upcoming.where(price: 0.0).order(:name) }
  scope :recent, ->(max=3) { past.limit(max) }

  def free?
    price.blank? || price.zero?
  end

  def spots_left
    if capacity.zero?
      0
    else
      capacity - registrations.size
    end
  end

  def sold_out?
    spots_left.zero?
  end


  def to_param
      slug
  end

  def generate_slug
    self.slug  ||= name.parameterize if name
  end






end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/registration.rb
class Registration < ApplicationRecord

  belongs_to :event
  belongs_to :user
  
  HOW_HEARD_OPTIONS = [ 
    'Newsletter',
    'Blog Post',
    'Twitter',
    'Web Search',
    'Friend/Coworker',
    'Other'
  ]
  
  validates :how_heard, 
            inclusion: { in: HOW_HEARD_OPTIONS }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event
  
  validates :name, presence: true

  validates :email, presence: true,                   
                    format: /\A\S+@\S+\z/,
                    uniqueness: { case_sensitive: false }

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  
  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in first!"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access!"
    end
  end

  def current_user_admin?  
    current_user && current_user.admin?
  end

  helper_method :current_user_admin?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  def index
    case params[:scope]
    when 'past'
      @events = Event.past
    when 'free'
      @events = Event.free
    when 'recent'
      @events = Event.recent
    else
      @events = Event.upcoming
    end
  end

  def show

    @likers = @event.likers

    if current_user
      @current_like = current_user.likes.find_by(event_id: @event.id)
    end

    @categories = @event.categories
  end

  def edit

  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event successfully updated!"
    else
      render :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "Event successfully created!"
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, alert: "Event successfully deleted!"
  end

private

  def set_event
    @event = Event.find_by!(slug: params[:id])
  end

  def event_params
    params.require(:event).
      permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity, :category_ids => [])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :require_signin
  before_action :set_event

  def create
    @event.likes.create!(user: current_user)
    redirect_to @event, notice: "Glad you liked it!"
  end

  def destroy
    like = current_user.likes.find(params[:id])
    like.destroy
    redirect_to @event, notice: "Sorry you unliked it!"
  end

private

  def set_event
    @event = Event.find_by!(slug: params[:event_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}!"
      redirect_to(session[:intended_url] || user)
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You're now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @registrations = @user.registrations
    @liked_events = @user.liked_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new
    end 
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, alert: "Account successfully deleted!"
  end

private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    if content_for?(:title)
      "Events - #{content_for(:title)}"
    else
      "Events"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, "Free")
    else
      number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag event.image_file_name
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def register_link_for(event)
    if event.sold_out?
      content_tag(:strong, "Sold Out!")
    else
      hint = content_tag(:span, "Only #{pluralize(event.spots_left, 'spot')} left!", class: 'scarcity')
      link_to "Register! #{hint}".html_safe, new_event_registration_path(event), class: 'button ok register'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>  
    Copyright &copy; 2016 The Pragmatic Studio
  </p>  
  <p>
    For educational purposes only.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Events', root_path %></h1>
    <nav>
      <p>
        <% if current_user %>
          <%= link_to current_user.name, current_user %>
          <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
        <% else %>
          <%= link_to 'Sign In', new_session_path, class: 'button' %>
          <%= link_to 'Sign Up', signup_path, class: 'button' %>
        <% end %>
      </p>  
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>  
      <li class="events">
        <%= link_to "Upcoming", events_path, class: 'button' %>
      </li>
      <li class="events">
        <%= link_to 'Past', filtered_events_path(:past), class: 'button' %>
      </li>
      <li class="events">
        <%= link_to 'Free', filtered_events_path(:free), class: 'button' %>
      </li>
      <li class="events">
        <%= link_to 'Recent', filtered_events_path(:recent), class: 'button' %>
      </li>
      <% if current_user_admin? %>
        <li class="create-event">
          <%= link_to 'Add New Event', new_event_path, class: 'button' %>
        </li>
      <% end %>
    </ul>
  </nav>
  <%= content_for(:side) %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>

  <div id="wrapper">

    <%= render "layouts/flashes"  %>

    <div id="container">
      <%= render "layouts/sidebar" %>
      <section id="content">
        <%= yield %>
      </section>
    </div>

  </div>

  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section id="errors">
    <header>
      <h2>
        Oops! Your form could not be saved.
      </h2>
      <h3>
        Please correct the following 
        <%= pluralize(object.errors.size, "error") %>:
      </h3>
    </header>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </section>
<% end %>